### ISSUE TITLE
no backup since 13/11/2020

### ISSUE THREAD

**Issue by ilsalgo** [petergardfjall/garminexport#64] opened 2020-11-16 06:59 UTC
No activity backup since 13/11/2020 for me.
Garminexport see 3 activity to backuped but not download it.

**Comment by petergardfjall** [comment] 2020-11-16 14:10
Could you provide more details? Could this be related to https://github.com/petergardfjall/garminexport/issues/63?
Did you try updating to the newest version?

**Comment by ilsalgo** [comment] 2020-11-16 15:11
Yes, I have update and it all worked out until yesterday,
Attached terminal screenshot
![garminexport](https://user-images.githubusercontent.com/32997790/99269228-64cda880-2826-11eb-95d9-0e975965dc21.jpg)

**Comment by petergardfjall** [comment] 2020-11-18 06:56
I have no trouble backing up with the latest version. Please run with `--log-level DEBUG` and show the output.

**Comment by ilsalgo** [comment] 2020-11-18 07:40
I assume that there's a problem in tcx file... possible to skip?
![screen](https://user-images.githubusercontent.com/32997790/99499823-c18da800-2979-11eb-8c91-d89d001f6b0a.jpg)

**Comment by petergardfjall** [comment] 2020-11-18 08:11
Looks like a server-side error for that particular activity. You can try with `--ignore-errors`.

**Comment by petergardfjall** [comment] 2020-11-18 08:13
Can you export the tcx file via the web (that is when visiting the activity at https://connect.garmin.com)?

**Comment by ilsalgo** [comment] 2020-11-18 08:22
I hadn't done the test from Garmin Connect and it doesn't work from there either, it returns the same error.
sorry for inconvenience.

**Comment by petergardfjall** [comment] 2020-11-18 11:53
No problem. It would be interesting to know what the problem is with your activity. How did you upload it to Garmin?

**Comment by ilsalgo** [comment] 2020-11-18 12:48
Apparently the starting point of a lap is missing from the file, if you export the activity as .fit or .gpx there are no problems, instead in the .tcx format it finds this inconvenience and generates the error.

I tried to edit the activity manually but can't resolve

**Comment by petergardfjall** [comment] 2020-11-18 18:15
Ok, I think that there's not much to do about this on the client side so I'll close the issue.

**Closed by petergardfjall** 2020-11-18 18:15 UTC
