### ISSUE TITLE
export currently not working

### ISSUE THREAD

**Issue by frechina** [petergardfjall/garminexport#23] opened 2018-04-05 09:01 UTC
It seems garmin removed 
https://connect.garmin.com/legacy/session

503 Service Unavailable
No server is available to handle this request.

Anyone fixing this?

**Comment by jedie** [comment] 2018-08-21 17:27
Very sad :(

**Comment by dlenski** [comment] 2018-08-21 18:20
I have no trouble logging in, but then the `activitySummary` endpoint fails. As usual, Garmin has monkeyed with their available API endpoints in various ways.

Also as usual, Tapiriik has updated to make itself work with the latest API endpoints, and cribbing off of its source code would be a good way to get this working again:

https://github.com/cpfair/tapiriik/blob/master/tapiriik/services/GarminConnect/garminconnect.py

(It looks like the `activitySummary` endpoint has moved to `https://connect.garmin.com/modern/proxy/activity-service/activity/{activityId}`.)

**Comment by ajaiantilal** [comment] 2018-08-21 18:27
I did run into this issue in May, but when i updated it to the latest Apr commit the issue went away. This code still seems to be working for me and i can download all my activities

**Comment by petergardfjall** [comment] 2018-08-30 17:57
I believe that this should be fixed with 01a08e1. Apparently attempting to download a .fit file for an activity without a .fit file now results in a `500` response (used to be `404`, which makes a lot more sense).

A lot of different issues seem to be implied by comments in this issue, but I'm unsure of which are actual issues with the code and which are caused by shaky Garmin services. Since I've just run a full backup of my own data without issues I'm assuming things are working again. Feel free to re-open (or open a new issue) if your problem persists.

@dlenski The code should already have been updated to make use of the new endpoint, so that cannot be the reason things are going awry.

**Closed by petergardfjall** 2018-08-30 17:57 UTC
