### ISSUE TITLE
upload_activity.py error line 60

### ISSUE THREAD

**Issue by benquan** [petergardfjall/garminexport#11] opened 2016-11-03 11:46 UTC
Hi Peter 

I am testing upload_activity.py but getting the following error.

Any guides?

$./upload_activity.py yyy@gmail.com ExampleWeights.fit 
Enter password: 
2016-11-03 05:40:23,699 [INFO] authenticating user ...
2016-11-03 05:40:30,666 [INFO] uploading activity file ExampleWeights.fit ...
2016-11-03 05:40:30,924 [ERROR] failed with exception: failed to upload {} for activity
Traceback (most recent call last):
  File "./upload_activity.py", line 60, in <module>
    id = client.upload_activity(args.activity, name=args.name, description=args.description, private=args.private)
  File "/Users/ben/venv.garminexport/src/garminexport/garminexport/garminclient.py", line 52, in check_session
    return client_function(*args, **kwargs)        
  File "/Users/ben/venv.garminexport/src/garminexport/garminexport/garminclient.py", line 429, in upload_activity
    raise Exception(u"failed to upload {} for activity")
Exception: failed to upload {} for activity

**Comment by dlenski** [comment] 2016-11-03 17:44
Hi @benquan, I actually wrote `upload_activity.py`. I just tried it and it's working fine for me (with a `.tcx` file; I don't have a device that generates `.fit` files).

Garmin Connect recently changed their authentication process in a way that made a lot of external apps, like [tapiriik](https://tapiriik.com/), unable to connect until users go in and reset their passwords. I don't really understand the details but you may be running into that issue here :(

**Comment by petergardfjall** [comment] 2016-11-03 19:38
Thanks @dlenski for chipping in! Do you have any further details on those issues (like some filed issue/forum thread or similar)?

I have, myself, had some trouble recently with not being able to export activities to gpx and tcx format (not even from the GC user interface itself).
I wind up with ugly Java stack traces like:
```
java.lang.RuntimeException: System error : Invalid or empty activity 
	com.garmin.connect.service.download.activityexport.provider.ActivityTcxSerializer.createActivityTcxComponent(ActivityTcxSerializer.java:179)
	com.garmin.connect.service.download.activityexport.provider.ActivityTcxSerializer.buildDocument(ActivityTcxSerializer.java:79)
	com.garmin.connect.service.download.activityexport.provider.ActivityTcxSerializer.serialize(ActivityTcxSerializer.java:68)
	com.garmin.connect.service.download.activityexport.provider.ActivityProvider.writeTo(ActivityProvider.java:38)
	com.garmin.connect.service.download.activityexport.provider.ActivityProvider.writeTo(ActivityProvider.java:21)
	com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1448)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	org.springframework.security.oauth.provider.filter.ProtectedResourceProcessingFilter.onValidSignature(ProtectedResourceProcessingFilter.java:87)
	org.springframework.security.oauth.provider.filter.OAuthProviderProcessingFilter.doFilter(OAuthProviderProcessingFilter.java:168)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	com.netflix.hystrix.contrib.requestservlet.HystrixRequestContextServletFilter.doFilter(HystrixRequestContextServletFilter.java:53)
```

Anything you've experienced?

**Comment by dlenski** [comment] 2016-11-03 20:16
@petergardfjall,
I had issues with Tapiriik similar to [tapiriik #254](https://github.com/cpfair/tapiriik/issues/254) and [tapiriik #255](https://github.com/cpfair/tapiriik/issues/255). These went away after I reset my password as suggested.

I haven't had any problems with `garminexport`, but haven't been using it all that much recently. I just tried exporting an activity to TCX from the GC website, and it worked fine for me.

Is it possible that Garmin's APIs are rejected calls from _their own site_ due to their authentication changes? :-1:

**Comment by petergardfjall** [comment] 2016-12-15 08:11
@benquan: is this still an issue for you?

**Comment by petergardfjall** [comment] 2017-02-14 09:44
Can neither reproduce nor get feedback from reporter. Closing ...

**Closed by petergardfjall** 2017-02-14 09:44 UTC
