### ISSUE TITLE
failed with exception: auth failure: unable to extract flowExecutionKey

### ISSUE THREAD

**Issue by pavlinux** [petergardfjall/garminexport#16] opened 2017-05-11 15:36 UTC
Running virtualenv with interpreter /usr/bin/python2
New python executable in venv.garminexport/bin/python2
Not overwriting existing python script venv.garminexport/bin/python (you must use venv.garminexport/bin/python2)
Installing setuptools, pip...done.
2017-05-11 18:17:50,025 [INFO] backing up formats: fit
2017-05-11 18:17:50,033 [INFO] authenticating user ...
2017-05-11 18:17:50,806 [ERROR] failed with exception: auth failure: unable to extract flowExecutionKey: https://sso.garmin.com/sso/login:

**Comment by inginero** [comment] 2017-05-12 02:27
I am observing the same issue as of 5/11/2017

**Comment by petergardfjall** [comment] 2017-05-12 18:12
Thanks for reporting. I'm looking into it. Seems like Garmin has (yet again...) changed their authentication process.

**Comment by dlenski** [comment] 2017-05-12 18:49
:frowning_face: 

Is Garmin doing this to intentionally bork 3rd-party applications, or are they just incompetent?

**Comment by petergardfjall** [comment] 2017-05-12 18:52
Good question. In either case, I *think* I'm onto a solution..

**Comment by pavlinux** [comment] 2017-05-13 16:14
https://github.com/cpfair/tapiriik/commit/fabd4d4bfed270fa300f68de0a08218d684d1ab5

**Comment by petergardfjall** [comment] 2017-05-14 06:56
With the latest commit, things appear to be working again on my end. Would anyone care to try it out before I close the issue?

https://github.com/petergardfjall/garminexport/commit/aaed3f44bba4442227512d1f872656eee73fa949

**Comment by spawn-github** [comment] 2017-05-14 14:53
Works for me. Thanks!

**Comment by inginero** [comment] 2017-05-14 15:13
Confirmed as working on my end as well.  Thanks for the update, Peter!

**Closed** 2017-05-14 15:32 UTC

**Comment by dlenski** [comment] 2017-05-14 21:25
Same here, working for me as well. Thanks, @petergardfjall!

However, login no longer works with my GC username, but only my email address. (Garmin changing random @#$* for no reason, naturally :-1:)
